language: cpp

os:
  - linux
  - osx

osx_image: xcode12

compiler:
  - clang
  - gcc

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt update ;
      sudo apt install g++ qt5-default qttools5-dev qttools5-dev-tools qtscript5-dev qtbase5-private-dev libqt5x11extras5-dev libgstreamer{-plugins-base,}1.0-dev zip libx11-dev libtag1-dev ;
      sudo apt install fluxbox xvfb ;
      sudo apt install gstreamer1.0-plugins-good gstreamer1.0-tools ;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install pkgconfig qt5 gstreamer gst-plugins-base taglib ;
      brew install gst-plugins-good ;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      Xvfb :99 &
      export DISPLAY=:99 ;
      sleep 3 ;
      fluxbox 2>/dev/null &
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH=/usr/local/opt/qt/bin:$PATH ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./configure --tests ;
      make -j$(grep processor /proc/cpuinfo | wc -l) ;
      ./test ;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./configure --tests;
      make -j$(sysctl -n hw.ncpu) ;
    fi


