language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

install:
  - sudo apt-get install libqt4-dev qt4-qmake libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev zip libx11-dev libtag1-dev
  - sudo apt-get install fluxbox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - fluxbox 2>/dev/null &

script:
  - ./configure --taglib --no-gstreamer-tagreader --tests
  - make -j`grep processor /proc/cpuinfo | wc -l`
  - ./test
